# Site settings
title: Hub-Travel
email:
description: > # This is for traveling and for fun
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown


collections:
  services:
    output: true
